# https://docs.docker.com/compose/compose-file/
version: '3.7'
services:

  stack:
    build: .
    command: sh -c 'stack --version && exec tail -f /dev/null'
    entrypoint: []
    environment:
      STACK_ROOT: /opt/monadoc/.stack/root
      STACK_WORK: .stack/work
    init: true
    volumes:
      - ./:/opt/monadoc
    working_dir: /opt/monadoc

  postgres:
    image: postgres:11.5-alpine
    init: true
    ports:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

  terraform:
    command: sh -c 'terraform version && exec tail -f /dev/null'
    entrypoint: []
    environment:
      AWS_ACCESS_KEY_ID: null
      AWS_DEFAULT_REGION: null
      AWS_SECRET_ACCESS_KEY: null
    image: hashicorp/terraform:0.12.12
    init: true
    volumes:
      - ./:/opt/monadoc
    working_dir: /opt/monadoc

volumes:
  postgres: null
